#include "model.h"
#include "render.h"
#include <curses.h>
#include <stdbool.h>
#include <stdio.h>

static maze_t maze = {
    {CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL,
     CELL_WALL, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED,
     CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_WALL, CELL_WALL, CELL_PATH_UNVISITED,
     CELL_WALL, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED,
     CELL_WALL, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED,
     CELL_WALL, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED,
     CELL_WALL, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED,
     CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL, CELL_WALL,
     CELL_WALL, CELL_WALL, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED,
     CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_PATH_UNVISITED, CELL_WALL},
    {CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL,
     CELL_WALL, CELL_WALL}};

static void step_callback(const maze_t *restrict maze, const Point_t *restrict current) {
    render_maze(*maze);
    render_current_point(*current);
    refresh();
    getch();
}

int main(void) {
    init_renderer();

    int result = find_path(maze, (Point_t){1, 1}, (Point_t){8, 8}, step_callback);
    if (result != 0) {
        fprintf(stderr, "Error: find_path() returned %d\n", result);
        return 1;
    }
    getch();

    destroy_renderer();
    return 0;
}
