#include "model.h"
#include "render.h"
#include <curses.h>
#include <stdbool.h>
#include <stdio.h>

static cell_type_t maze[MAZE_HEIGHT][MAZE_WIDTH] = {
    {CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL,
     CELL_WALL, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_WALL, CELL_WALL, CELL_WALL, CELL_PATH, CELL_WALL, CELL_WALL,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_WALL,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_WALL,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_WALL,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_PATH, CELL_PATH,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_WALL, CELL_PATH, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH, CELL_PATH,
     CELL_PATH, CELL_WALL},
    {CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL, CELL_WALL,
     CELL_WALL, CELL_WALL}};

int main(void) {
    initscr();
    raw();
    keypad(stdscr, true);
    noecho();

    render_maze(maze);
    refresh();
    getch();

    endwin();
    return 0;
}
